### ISSUE TITLE
OPAT Dashboard

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-dashboard#1]
Assume unit of interest == Month
I think things we might show are
- Number of referrals
  - Number of referrals by referring team
- Accepted referrals
- Number of patients completed OPAT

**Comment by davidmiller** [comment]
@michaeledwardmarks - presume that your recent forray into data exploration means you have a better sense of this now?

**Comment by michaeledwardmarks** [comment]
Yes.
I think the CCG dataset essentially which is mostly:
- [ ] My OPAT DO.file
- Duration of OPAT, Type of Lines and average length, duration of OPAT, who gave the drugs
- [ ] Number of Referrals per month
- [ ] Referral by referring team 
  https://github.com/openhealthcare/opal-opat/issues/16
  https://github.com/openhealthcare/opal-opat/issues/19
- [ ] Outcomes by Diagnostic Category
  https://github.com/openhealthcare/opal-opat/issues/10

**Comment by davidmiller** [comment]
Given inactivity, closing this.
