### ISSUE TITLE
Micro + Liaison Lists

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-dashboard#2]
Core things we might show
- Number of patients
- Number of Clinical Advice Modals completed
- Frequency of each tick box (e.g clinical advice, change in Abx)

**Comment by michaeledwardmarks** [comment]
Also (on review of earlier elCID issues) 
- Reason for interaction (from clinical advice modal)
- Diagnosis

**Comment by davidmiller** [comment]
Given inactivity, closing this.
