### ISSUE TITLE
Inpatient Lists

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-dashboard#3]
- Number of patients
- % Completion of Presenting Complaint
- Number of Discharge diagnoses
- % Completion of Diagnosis confirmation by consultant

**Comment by davidmiller** [comment]
@michaeledwardmarks Didn't Maddy specifically ask for a set of things to be in these reports?

c.f. Maybe https://github.com/openhealthcare/elcid/issues/96#issuecomment-35429713 ?

Is that a different thing or a superset, or should this be amended?

**Comment by michaeledwardmarks** [comment]
Also (on review of earlier elCID issues) 
- Age and sex distribution
- length of stay distribution

**Comment by GabPoll** [comment]
Also % of patients with no entry in antimicrobial modal?

On review of 1st year of elCID data, this was >50% for an infectious diseases service!

**Comment by michaeledwardmarks** [comment]
% patients with no travel entry....

**Comment by davidmiller** [comment]
Given inactivity, closing this.
