### ISSUE TITLE
Allow parameters in dashboards

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-dashboard#6]
Current view gives realtime data feed (super cool)

I was thinking about online banking where you get a dashboard of recent transactions and then a by month statement.

We could consider same here - e.g show me the ID-Liaison dashboard for Feb 2014??

**Comment by davidmiller** [comment]
The enabling feature here is allowing users to alter parameters that apply to the current dashboard.

We should allow that where appropriate!

**Comment by davidmiller** [comment]
Given inactivity, closing this.
